CONNECT C##POS_USER/secret

CREATE OR REPLACE TRIGGER SEQ_TRG_pos_customer
BEFORE INSERT ON pos_customer
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
  SELECT SEQ_pos_customer.NEXTVAL
  INTO: NEW.pos_customer_id
  FROM DUAL;
END;
/