CONNECT C##POS_USER/secret

CREATE OR REPLACE TRIGGER SEQ_TRG_pos_sell
BEFORE INSERT ON pos_sell
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
  SELECT SEQ_pos_sell.NEXTVAL
  INTO: NEW.pos_sell_id
  FROM DUAL;
END;
/